apiVersion: apps/v2
kind: Deployment
metadata:
  name: nginx-app
  labels:
    managed-by: dso
spec:
  replicas: 3
  selector:
    matchLabels:
      application: nginx-app
  template:
    metadata:
      labels:
        application: nginx-app
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/sapient-tracer-417700/app3/app-image:v2
          ports:
            - name: http
              containerPort: 80